### ISSUE TITLE
[swiftlint: error while loading shared libraries: libswiftCore.so: cannot open shared object file: No such file or directory]

### ISSUE THREAD

**Issue by engali94** [norio-nomura/docker-swiftlint#11]
I am trying to install the latest image in a container 
after running swift lint in the directory that contains swift files I got this error
[swiftlint: error while loading shared libraries: libswiftCore.so: cannot open shared object file: No such file or directory]

it seems that the buildpack does not copy all the shared libraries from the Swift toolchain correctly?

**Comment by norio-nomura** [comment]
The latest image uses a static linked `swiftlint`, so this issue should be resolved.
