### ISSUE TITLE
Please update for 0.47.0

### ISSUE THREAD

**Issue by stackotter** [norio-nomura/docker-swiftlint#26]
Firstly, thanks for hosting this super simple to use SwiftLint action! I'm requesting that you update this to SwiftLint 0.47.0 because it contains support for globs within excluded paths which is super useful because I need to exclude lots of generated files.

**Comment by sirnacnud** [comment]
Any chance for an update? 0.48.0 is out now.

**Comment by jase88** [comment]
`0.49.1` is latest and 0.50 is already rc ;)

**Comment by norio-nomura** [comment]
Updated to 0.49.1

**Comment by stackotter** [comment]
Awesome, thanks! 🎉
